---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/spreaeb3/public_html/cleansingwaters.site/
    - /bin/rsync -av --delete \
      --exclude '.git*' \
      --exclude '.cpanel.yml' \
      ./ $DEPLOYPATH
